### ISSUE TITLE
pyproject.toml

### ISSUE THREAD

**Issue by arokem** [noahbenson/pimms#4]
When installing with newer versions of pip, I am getting: 

```
DEPRECATION: pimms is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
```
I think it should be straightforward in this case, and could put in a PR, if you are interested in making this change.

**Comment by noahbenson** [comment]
Ahh, yes, I have actually been meaning to do this for awhile but haven't quite gotten around to it yet. I have not used `pyproject.toml` files yet—if you want to make a pull request that would be great, but also feel free to point me toward a good example project with the file that's similar-ish? Thanks!
